ardupilot_default_airframe: gazebo-iris
ardupilot_dir: ~/ardupilot
global_coordinates:
  altitude: 90.0
  latitude: -6.3653130531311035
  longitude: 106.82479858398438
px4_default_airframe: gazebo-classic_iris
px4_dir: ~/PX4-Autopilot
